version: '3.3'
services:
    solr:
        image: solr:7
        hostname: solr1
        restart: unless-stopped
        ports:
          - 8983:8983
        environment:
            SOLR_HEAP: 2g
        command: -c
    roda:
      image: keeps/roda:latest
      restart: unless-stopped
      ports:
        - 8080:8080
        - 5005:5005 # remote debug
      depends_on:
        - solr
      environment:
        # Solr Cloud configuration
        - RODA_CORE_SOLR_TYPE=CLOUD
        - RODA_CORE_SOLR_CLOUD_URLS=solr:9983
        - SOLR_NUM_SHARDS=4
        - SOLR_MAX_SHARDS_PER_NODE=16
        - SOLR_REPLICATION_FACTOR=1

        # Remote debug
        - JPDA_ADDRESS=5005
        - JPDA_TRANSPORT=dt_socket
      command: catalina.sh jpda run
